'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('lists', [
      {
        project_id: '1',
        box_id: '3',
        list: "Loki's scepter",
        description: 'at Eastern European country of Sokovia commences',
        type: 'TODO',
        status: 'DOING',
        important: 'IMPORTANT',
        score: 3,
        project_pin: 2,
        order: 1,
        created_at: new Date(new Date().setDate(new Date().getDate() - 7)),
        updated_at: new Date(new Date().setDate(new Date().getDate() - 7)),
        list_deadline: '2021-01-31',
      },
      {
        project_id: '1',
        box_id: '1',
        list: 'Pietro and Wanda Maximoff',
        description:
          'Pietro can move at superhuman speeds, while Wanda possesses a powerful plethora of psionic powers.',
        type: 'TODO',
        status: 'TODO',
        important: 'IMPORTANT',
        score: 3,
        project_pin: 0,
        order: 1,
        created_at: new Date(new Date().setDate(new Date().getDate() - 3)),
        updated_at: new Date(new Date().setDate(new Date().getDate() - 3)),
        list_deadline: '2021-01-31',
      },
      {
        project_id: '1',
        box_id: '1',
        list: 'Ultron',
        description: 'He think that the only way to save Earth is to eradicate humanity.',
        type: 'TODO',
        status: 'TODO',
        important: 'IMPORTANT',
        score: 3,
        project_pin: 1,
        order: 2,
        created_at: new Date(new Date().setDate(new Date().getDate() - 1)),
        updated_at: new Date(new Date().setDate(new Date().getDate() - 1)),
        list_deadline: '2021-01-31',
      },
      {
        project_id: '1',
        box_id: '4',
        list: 'ล้ม S.H.I.E.L.D. ซะ',
        description: 'Hydra เยอะเกิ๊น',
        type: 'TODO',
        status: 'DONE',
        important: 'NOTHING',
        score: 2,
        project_pin: 0,
        order: 1,
        created_at: new Date(new Date().setDate(new Date().getDate() - 365)),
        updated_at: new Date(new Date().setDate(new Date().getDate() - 365)),
        list_deadline: '2021-01-31',
      },
      {
        project_id: '1',
        box_id: '1',
        list: 'Add THOR PLEASE',
        description: 'Has any one know Thor Username?',
        type: 'TODO',
        status: 'TODO',
        important: 'MAY',
        score: 1,
        project_pin: -1,
        order: 3,
        created_at: new Date(new Date().setTime(new Date().getTime() - 540140000)),
        updated_at: new Date(new Date().setTime(new Date().getTime() - 540140000)),
        list_deadline: '2021-01-31',
      },
      {
        project_id: '1',
        box_id: '5',
        list: "Loki's scepter",
        description: 'https://res.cloudinary.com/dmtmyh1hg/image/upload/v1607670360/marvel/loki-scepter_z1jyku.jpg',
        type: 'PICTURE',
        status: 'NOTHING',
        important: 'NOTHING',
        project_pin: 1,
        order: 1,
        created_at: new Date(new Date().setTime(new Date().getTime() - 540130000)),
        updated_at: new Date(new Date().setTime(new Date().getTime() - 540130000)),
        list_deadline: '2021-01-31',
      },
      {
        project_id: '3',
        box_id: '13',
        list: 'แอบเข้าโซนหนังสือต้องห้าม',
        description: 'มอมเหล้าหว่องแล้วจ๊กมาสัก2-3เล่ม',
        type: 'TODO',
        status: 'TODO',
        important: 'IMPORTANT',
        project_pin: 1,
        order: 1,
        created_at: new Date(new Date().setTime(new Date().getTime() - 540240000)),
        updated_at: new Date(new Date().setTime(new Date().getTime() - 540240000)),
        list_deadline: '2021-01-02',
      },
      {
        project_id: '3',
        box_id: '14',
        list: 'ชวนหว่องไปจิบชาที่ลอนดอน',
        description: 'แอบถามเวยเวยว่าหว่องชอบชาอะไร',
        type: 'TODO',
        status: 'DOING',
        important: 'MUST',
        project_pin: 1,
        order: 1,
        created_at: new Date(new Date().setTime(new Date().getTime() - 540280000)),
        updated_at: new Date(new Date().setTime(new Date().getTime() - 540280000)),
        list_deadline: '2021-01-01',
      },
      {
        project_id: '3',
        box_id: '15',
        list: 'ไปรักษาตัวที่ Kamar-Taj',
        description: 'ความหวังสุดท้าย ยังไงก็ต้องลองดู',
        type: 'TODO',
        status: 'DONE',
        important: 'MUST',
        project_pin: 1,
        order: 2,
        created_at: new Date(new Date().setDate(new Date().getDate() - 1800)),
        updated_at: new Date(new Date().setDate(new Date().getDate() - 1800)),
        list_deadline: '2016-01-31',
      },
      {
        project_id: '3',
        box_id: '15',
        list: 'นัดทำกายภาพบำบัด',
        description: 'อย่าลืมออกกำลังกายเยอะๆนะ',
        type: 'TODO',
        status: 'DONE',
        important: 'MUST',
        project_pin: 0,
        order: 1,
        created_at: new Date(new Date().setDate(new Date().getDate() - 2000)),
        updated_at: new Date(new Date().setDate(new Date().getDate() - 2000)),
        list_deadline: '2015-01-01',
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('lists', null, {});
  },
};
